### ISSUE TITLE
Scrolling issue on main class page

### ISSUE THREAD

**Issue by charlottevolk** [KTregubov/Project-Harkness#1]
Login: cvolk@bayviewglen.ca
Password: iiiiii

When a new class is created that has no previous harkness tables, the class page doesn't allow you to scroll all the way to the top (cuts off part of class name, course code, and add harkness button)

![image](https://user-images.githubusercontent.com/31663144/58925886-2b2edd80-8717-11e9-8393-a67d3c58f671.png)

**Comment by KTregubov** [comment]
Fixed in next commit.
