### ISSUE TITLE
Linking problem on main class page

### ISSUE THREAD

**Issue by charlottevolk** [KTregubov/Project-Harkness#2]
On the main class page, the "+" button and the button with three vertical dots both link to localhost:8080/new/harkness. The "+" button works fine, but the vertical dots button takes you to an error page:

![image](https://user-images.githubusercontent.com/31663144/58925965-7943e100-8717-11e9-8928-3cee2a6eea15.png)

**Comment by KTregubov** [comment]
Alex is fixing this in the next version to redirect all bad traffic to the 404 page.
